countries=["Afghanistan","Albania","Algeria","Andorra","Angola","Antigua & Deps","Argentina","Armenia",
"Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh","Barbados","Belarus","Bermuda",
"British Virgin Islands","Belgium","Belize","Benin","Bhutan","Bolivia","Bosnia Herzegovina",
"Botswana","Brazil","Brunei","Bulgaria","Burkina","Burundi","Cambodia","Curaçao","Cameroon",
"Canada","Cape Verde","Central African Rep","Chad","Chile","Channel Islands","China","Colombia",
"Comoros","Congo","Congo {DemocraticRep}","Costa Rica","Côte d'Ivoire","Cayman Islands",
"Croatia","Cuba","Cyprus","Czech Republic","Denmark","Djibouti","Dominica","Darussalam",
"Dominican Republic","Timor-Leste","Ecuador","Egypt","ElSalvador","Equatorial Guinea",
"Eswatini","Eritrea","Estonia","Ethiopia","Fiji","Finland","Faroe Islands","France",
"French Polynesia","Gabon","Gambia","Georgia","Germany","Ghana","Greece","Grenada","Guatemala",
"Guinea","Guinea-Bissau","Guyana","Gibraltar","Haiti","Honduras","Hong Kong",
"Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland {Republic}",
"Israel","Italy","Isle of Man","Ivory Coast","Jamaica","Japan","Jordan","Kazakhstan",
"Kenya","Kiribati","Korea North","Korea South","Kosovo","Kuwait","Kyrgyzstan",
"Laos","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein","Lithuania",
"Luxembourg","Macedonia","Madagascar","Malawi","Malaysia","Maldives","Mali","Macao","Malta",
"Marshall Islands","Mauritania","Mauritius","Mexico","Micronesia","Moldova","Monaco","Mongolia",
"Montenegro","Morocco","Mozambique","Myanmar","Namibia","Nauru","Nepal","Netherlands",
"New Zealand","Nicaragua","Niger","Nigeria","Norway","New Caledonia","Northern Mariana Islands",
"Oman","Pakistan","Palau","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Puerto Rico",
"Poland","Portugal","Qatar","Romania","Russian Federation","Rwanda","St Kitts & Nevis","St Lucia",
"Saint Vincent & the Grenadines","Samoa","San Marino","Sao Tome & Principe","St. Martin",
"Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Slovakia",
"Slovenia","Solomon Islands","Somalia","South Africa","South Sudan","Spain","Sri Lanka",
"Sudan","Suriname","Swaziland","Sweden","Switzerland","Syria","Taiwan","Tajikistan","Tanzania",
"Thailand","Togo","Tonga","Trinidad & Tobago","Tunisia","Turkey","Turkmenistan","TurksandCaicosIslands",
"Tuvalu","Uganda","Ukraine","United Arab Emirates","United Kingdom","United States","Uruguay","Uzbekistan",
"Vanuatu","Vatican City","Venezuela","Vietnam","Virgin Islands (U.S.)","Yemen","West Bank and Gaza","Zambia","Zimbabwe"]



highincome = [
"Andorra",
"Greece",
"Poland",
"Antigua & Deps",
"Portugal",
"Puerto Rico",
"Australia",
"Hong Kong",
"Qatar",
"Austria",
"Hungary",
"San Marino",
"Bahamas",
"Iceland",
"Saudi Arabia",
"Bahrain",
"Ireland {Republic}",
"Seychelles",
"Barbados",
"Isle of Man",
"Singapore",
"Belgium",
"Israel",
"Bermuda",
"Italy",
"Slovakia",
"British Virgin Islands",
"Japan",
"Slovenia",
"Brunei",
"Darussalam",
"Korea South",
"Spain",
"Canada",
"Kuwait",
"St Kitts & Nevis",
"Cayman Islands",
"Latvia",
"St. Martin",
"Channel Islands",
"Liechtenstein",
"Sweden",
"Chile",
"Lithuania"
"Switzerland",
"Croatia",
"Luxembourg",
"Taiwan",
"Curaçao",
"Macao",
"Trinidad & Tobago",
"Cyprus",
"Malta",
"Turks and Caicos Islands",
"Czech Republic",
"Monaco",
"United Arab Emirates",
"Denmark",
"Nauru",
"United Kingdom",
"Estonia",
"Netherlands",
"United States",
"Faroe Islands",
"New Caledonia",
"Uruguay",
"Finland",
"New Zealand",
"Virgin Islands (U.S.)",
"France",
"Northern Mariana Islands",
"French Polynesia",
"Norway",
"Germany",
"Oman",
"Gibraltar",
"Palau"]

uppermiddleincome = [
"Albania",
"Gabon",
"Namibia",
"Samoa",
"Georgia",
"Macedonia",
"Argentina",
"Grenada",
"Panama",
"Armenia",
"Guatemala",
"Paraguay",
"Azerbaijan",
"Guyana",
"Peru",
"Belarus",
"Iraq",
"Romania",
"Bosnia Herzegovina",
"Jamaica",
"Russian Federation",
"Botswana",
"Jordan	",
"Serbia",
"Brazil",
"Kazakhstan",
"South Africa",
"Bulgaria",
"Kosovo",
"St Lucia",
"China",
"Lebanon",
"Saint Vincent & the Grenadines",
"Colombia",
"Libya",
"Suriname",
"Costa Rica ",
"Malaysia",
"Thailand"
"Cuba",
"Maldives",
"Tonga",
"Dominica",
"Marshall Islands",
"Turkey",
"Dominican Republic",
"Mauritius",
"Turkmenistan",
"Equatorial Guinea",
"Mexico",
"Tuvalu",
"Ecuador",
"Moldova",
"Fiji",
"Montenegro"]

lowmiddleincome = [
"Angola",
"Honduras",
"Philippines",
"Algeria",
"India ",
"Samoa",
"Bangladesh",
"Indonesia",
"Sao Tome & Principe",
"Belize",
"Iran",
"Senegal",
"Benin",
"Kenya",
"Solomon Islands",
"Bhutan",
"Kiribati",
"Sri Lanka",
"Bolivia",
"Kyrgyzstan",
"Tanzania",
"Cape Verde",
"Laos",
"Tajikistan",
"Cambodia",
"Lesotho",
"Timor-Leste",
"Cameroon",
"Mauritania",
"Tunisia",
"Comoros",
"Micronesia",
"Ukraine",
"Congo",
"Mongolia",
"Uzbekistan",
"Côte d'Ivoire",
"Morocco",
"Vanuatu",
"Djibouti",
"Myanmar",
"Vietnam",
"Egypt",
"Nepal",
"West Bank and Gaza",
"El Salvador",
"Nicaragua",
"Zambia",
"Nigeria",
"Zimbabwe",
"Eswatini",
"Ghana",
"Pakistan",
"Haiti",
"Papua New Guinea"]

income_groups = {
    "high_income": [
        "Andorra", "Antigua and Barbuda", "Aruba", "Australia", "Austria", "Bahamas, The", "Bahrain", "Barbados",
        "Belgium", "Bermuda", "British Virgin Islands", "Brunei Darussalam", "Canada", "Cayman Islands",
        "Channel Islands", "Chile", "Croatia", "Curaçao", "Cyprus", "Czech Republic", "Denmark", "Estonia",
        "Faroe Islands", "Finland", "France", "French Polynesia", "Germany", "Gibraltar", "Greece", "Greenland",
        "Guam", "Hong Kong SAR, China", "Hungary", "Iceland", "Ireland", "Isle of Man", "Israel", "Italy", "Japan",
        "Korea, Rep.", "Kuwait", "Latvia", "Liechtenstein", "Lithuania", "Luxembourg", "Macao SAR, China", "Malta",
        "Monaco", "Nauru", "Netherlands", "New Caledonia", "New Zealand", "Northern Mariana Islands", "Norway",
        "Oman", "Palau", "Panama", "Poland", "Portugal", "Puerto Rico", "Qatar", "San Marino", "Saudi Arabia",
        "Seychelles", "Singapore", "Sint Maarten (Dutch part)", "Slovak Republic", "Slovenia", "Spain",
        "St. Kitts and Nevis", "St. Martin (French part)", "Sweden", "Switzerland", "Taiwan, China",
        "Trinidad and Tobago", "Turks and Caicos Islands", "United Arab Emirates", "United Kingdom",
        "United States", "Uruguay", "Virgin Islands (U.S.)"
    ],
    "upper_middle_income": [
        "Albania", "Algeria", "American Samoa", "Argentina", "Armenia", "Azerbaijan", "Belarus", "Belize",
        "Bosnia and Herzegovina", "Botswana", "Brazil", "Bulgaria", "China", "Colombia", "Costa Rica", "Cuba",
        "Dominica", "Dominican Republic", "El Salvador", "Equatorial Guinea", "Fiji", "Gabon", "Georgia",
        "Grenada", "Guatemala", "Guyana", "Indonesia", "Iran, Islamic Rep.", "Iraq", "Jamaica", "Jordan",
        "Kazakhstan", "Kosovo", "Lebanon", "Libya", "Malaysia", "Maldives", "Marshall Islands", "Mauritius",
        "Mexico", "Moldova", "Montenegro", "Namibia", "North Macedonia", "Paraguay", "Peru", "Romania",
        "Russian Federation", "Samoa", "Serbia", "South Africa", "Sri Lanka", "St. Lucia",
        "St. Vincent and the Grenadines", "Suriname", "Thailand", "Tonga", "Turkey", "Turkmenistan", "Tuvalu",
        "Venezuela, RB", "Vietnam"
    ],
    "lower_middle_income": [
        "Angola", "Bangladesh", "Benin", "Bhutan", "Bolivia", "Cabo Verde", "Cambodia", "Cameroon", "Comoros",
        "Congo, Rep.", "Côte d'Ivoire", "Djibouti", "Egypt, Arab Rep.", "Eswatini", "Ghana", "Honduras",
        "India", "Kenya", "Kiribati", "Kyrgyz Republic", "Lao PDR", "Lesotho", "Mauritania",
        "Micronesia, Fed. Sts.", "Mongolia", "Morocco", "Mozambique", "Myanmar", "Nepal", "Nicaragua", "Nigeria",
        "Pakistan", "Papua New Guinea", "Philippines", "Sao Tome and Principe", "Senegal", "Solomon Islands",
        "Tajikistan", "Tanzania", "Timor-Leste", "Tunisia", "Ukraine", "Uzbekistan", "Vanuatu", "West Bank and Gaza",
        "Zambia", "Zimbabwe"
    ],
    "low_income": [
        "Afghanistan", "Burkina Faso", "Burundi", "Central African Republic", "Chad", "Congo, Dem. Rep.",
        "Eritrea", "Ethiopia", "Gambia, The", "Guinea", "Guinea-Bissau", "Korea, Dem. People's Rep.",
        "Liberia", "Madagascar", "Malawi", "Mali", "Niger", "Rwanda", "Sierra Leone", "Somalia", "South Sudan",
        "Sudan", "Syrian Arab Republic", "Togo", "Uganda", "Yemen, Rep."
    ]
}



questions = [{
    "question": "Do you have access to a clean source of water?",#0
  },{
    "question": "Do you have access to clean cooking fuels?", #1
  },{
    "question": "Do you have access to Electricty?", #2
  },{
    "question": "Do you have access to the Internet?", #3
  },{
    "question": "Do you have access to Health services?", #4
  },{
    "question": "What most describes your financial situation last year?", #5
  },{
    "question": "What is your level of education?", #6
  },{
    "question": "How much do you live on daily?", #7
  }]

answer = [{
    #"question": "Do you have access to a clean source of water?",
    "71": "Yes",
    "100": "No",
  },{
    #"question": "Do You have access to clean cooking fuels?",
    "60": "Yes",
    "100": "No",
  },{
    #"question": "Do You have access to electricty?",
    "87": "Yes",
    "100": "No",
  },{
    #"question": "Do You have access to internet?",
    "59": "Yes",
    "100": "No",
  },{
    #"question": "Do you have access to Healthcare?",
    "94": "Yes",
    "100": "No",
  },{
    #"question": "What most describes your financial situation last year?",
    "100": "There were times in the past year when you were unable to afford food or shelter or struggled to afford both, and do not have family or friends who could help you in times of trouble.",
    "86": "There were times in the past year when you were unable to afford food or shelter or struggled to afford both, and do have family or friends who could help you in times of trouble.",
    "47": "There were not times in the past year when you struggled to afford food or shelter, and do have family or friends who could help you in times of trouble.",
  },{
    #"question": "What is your level of education?",
    "100":"None",
    "90": "Primary",
    "76": "Low secondary",
    "55": "Upper secondary",
    "38": "Post secondary",
  },{
    #"question": "How much do you live on daily?", #5
    "100": "2$ or less",
    "87": "2$ - 10$",
    "36": "10$ - 20$",
    "21": "20$ - 50$",
    "7": "50$+",
  }]
